# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: CDSS / TSTool (Developer)
pages:
- 'Introduction': index.md
- 'New Developer Setup':
  - 'Overview': dev-new/overview.md
- 'Development Tasks':
  - 'Overview': dev-tasks/overview.md
#  - 'Run Eclipse': dev-tasks/run-eclipse.md
#  - 'Designing Software': dev-tasks/designing-software.md
#  - 'Version Control with Git': dev-tasks/versioning.md
#  - 'Documenting': dev-tasks/documenting.md
#  - 'Troubleshooting Eclipse': dev-tasks/troubleshooting-eclipse.md
#  - 'Coding': dev-tasks/coding.md
#  - 'Compiling': dev-tasks/compiling.md
#  - 'Testing': dev-tasks/testing.md
#  - 'Deploying': dev-tasks/deploying.md
#  - 'FAQ for Cygwin': dev-tasks/faq-cygwin.md
#  - 'FAQ for Linux': dev-tasks/faq-linux.md
#  - 'FAQ for MinGW': dev-tasks/faq-mingw.md
- 'Resources': resources.md
- 'REFERENCE: Software Design':
  - 'Overview': software-design/overview.md
- 'REFERENCE: Deployed Environment':
  - 'Overview': deployed-env/overview.md
- 'REFERENCE: Development Environment':
  - 'Overview': dev-env/overview.md
  - 'Machine': dev-env/machine.md
  - 'Git': dev-env/git.md
  - 'Python and pip': dev-env/python.md
  - 'MkDocs': dev-env/mkdocs.md
  - 'Java 8': dev-env/java8.md
  - 'Eclipse': dev-env/eclipse.md
#  - 'Text Editor': dev-env/editor.md
  - 'KDiff3': dev-env/kdiff3.md
# Fill the following out later - may not need for TSTool
- 'REFERENCE: Initial Project Setup':
  - Overview: project-init/overview.md
#  - 'Create Development Home Folder': project-init/home-folder.md
#  - 'GitHub Git Repository': project-init/github.md
  - 'Eclipse Run Script': project-init/eclipse-run-script.md
  - 'Eclipse Workspace': project-init/eclipse-workspace.md
#  - 'Eclipse TSTool Project': project-init/eclipse-tstool-project.md
#  - 'Eclipse Folder Structure': project-init/eclipse-folder-structure.md
#  - 'Eclipse Make Targets': project-init/eclipse-make-targets.md
#  - 'Build Utility Scripts': project-init/build-util.md
#  - 'Documentation, Legacy  (Word)': project-init/doc.md
#  - 'Documentation, Developer (MkDocs)': project-init/doc-dev.md
#  - 'Documentation, User (MkDocs)': project-init/doc-user.md
#  - 'Documentation, API (Doxygen)': project-init/doc-doxygen.md
#  - 'Git StateMod History': project-init/git-statemod-history.md
# ------- configuration properties ---------------
# Use Material theme
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme: material
# Don't enable the repo URL because irritating edit icons are shown when editing really isn't allowed
#repo_url:  https://github.com/OpenWaterFoundation/cdss-app-tstool-doc-user
site_description:  CDSS TSTool (Developer)
site_author:  OpenCDSS
site_favicon:  'images/opencdss-favicon.ico'
copyright:  Copyright State of Colorado
# Use extra CSS to customize styles, based on theme
extra_css:
  - 'css/extra-material-theme.css'
markdown_extensions:
  - footnotes
