# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: CDSS / TSTool (Developer)
nav:
- 'Introduction': index.md
- 'New Developer Setup':
  - 'Overview': dev-new/overview.md
- 'Development Tasks':
  - 'Overview': dev-tasks/overview.md
  - 'OpenCDSS Coordination': dev-tasks/opencdss-coord/opencdss-coord.md
  - 'Run Eclipse': dev-tasks/run-eclipse/run-eclipse.md
  - 'Designing Software': dev-tasks/designing-software/designing-software.md
  - 'Troubleshooting Eclipse': dev-tasks/troubleshooting-eclipse/troubleshooting-eclipse.md
  - 'Coding': dev-tasks/coding/coding.md
  - 'Documenting': dev-tasks/documenting/documenting.md
  - 'Version Control': dev-tasks/version-control/version-control.md
  - 'Compiling': dev-tasks/compiling/compiling.md
  - 'Running': dev-tasks/running/running.md
  - 'Testing': dev-tasks/testing/testing.md
  - 'Building Installer': dev-tasks/building-installer/building-installer.md
  - 'Deploying': dev-tasks/deploying/deploying.md
  - 'Installing': dev-tasks/installing/installing.md
#  - 'FAQ for Cygwin': dev-tasks/faq-cygwin.md
#  - 'FAQ for Linux': dev-tasks/faq-linux.md
#  - 'FAQ for MinGW': dev-tasks/faq-mingw.md
- 'Resources': resources.md
- 'REFERENCE: Software Design':
  - 'Overview': software-design/overview.md
  - 'Repositories and Projects': software-design/repo/repo.md
  - 'Testing Framework': software-design/testing-framework/testing-framework.md
  - 'Documentation': software-design/documentation/documentation.md
  - 'User Interface (UI)': software-design/ui/ui.md
  - 'Java Runtime Environment (JRE)': software-design/jre/jre.md
  - 'TSTool Main Application': software-design/tstool-app/tstool-app.md
  - 'Command File and Command Syntax': software-design/command-syntax/command-syntax.md
  - 'Command Processor': software-design/command-processor/command-processor.md
  - 'Command': software-design/command/command.md
  - 'Command Factory': software-design/command-factory/command-factory.md
  - 'Command Status': software-design/commandstatus/commandstatus.md
  - 'Plugin Commands': software-design/plugin-commands/plugin-commands.md
  - 'Utility Packages': software-design/util/util.md
  - 'Commands that Read Time Series': software-design/command-read-ts/command-read-ts.md
  - 'Logging': software-design/logging/logging.md
  - 'Date/time Handling': software-design/datetime/datetime.md
  - 'Time Series': software-design/ts/ts.md
  - 'Datastores': software-design/datastores/datastores.md
  - 'Plugin Datastores': software-design/plugin-datastores/plugin-datastores.md
  - 'Tables': software-design/tables/tables.md
  - 'Data Products': software-design/data-products/data-products.md
  - 'Spreadsheet': software-design/spreadsheet/spreadsheet.md
  - 'Spatial Data': software-design/spatial/spatial.md
  - 'Templates': software-design/templates/templates.md
  - 'Development Roadmap': software-design/roadmap/roadmap.md
- 'REFERENCE: Deployed Environment':
  - 'Overview': deployed-env/overview.md
- 'REFERENCE: Development Environment':
  - 'Overview': dev-env/overview.md
  - 'Machine': dev-env/machine.md
  - 'Git': dev-env/git.md
  - 'Python and pip': dev-env/python.md
  - 'MkDocs': dev-env/mkdocs.md
  - 'Java 8': dev-env/java8.md
  - 'Eclipse': dev-env/eclipse.md
#  - 'Text Editor': dev-env/editor.md
  - 'KDiff3': dev-env/kdiff3.md
  - 'NSIS': dev-env/nsis.md
  - 'launch4j': dev-env/launch4j.md
# Fill the following out later - may not need for TSTool
- 'REFERENCE: Initial Project Setup':
  - Overview: project-init/overview.md
#  - 'Create Development Home Folder': project-init/home-folder.md
#  - 'GitHub Git Repository': project-init/github.md
  - 'Eclipse Run Script': project-init/eclipse-run-script.md
  - 'Eclipse Workspace': project-init/eclipse-workspace.md
#  - 'Eclipse TSTool Project': project-init/eclipse-tstool-project.md
#  - 'Eclipse Folder Structure': project-init/eclipse-folder-structure.md
#  - 'Eclipse Make Targets': project-init/eclipse-make-targets.md
#  - 'Build Utility Scripts': project-init/build-util.md
#  - 'Documentation, Legacy  (Word)': project-init/doc.md
#  - 'Documentation, Developer (MkDocs)': project-init/doc-dev.md
#  - 'Documentation, User (MkDocs)': project-init/doc-user.md
#  - 'Documentation, API (Doxygen)': project-init/doc-doxygen.md
#  - 'Git StateMod History': project-init/git-statemod-history.md
# ------- configuration properties ---------------
# Alphabetize
# ------------------------------------------------
copyright:  Copyright State of Colorado Department of Natural Resources
# ------------------------------------------------
# Use extra CSS to customize styles, based on theme
extra_css:
  - 'css/extra-material-theme.css'
# ------------------------------------------------
google_analytics:
 - 'UA-43023264-1'
 - auto
# ------------------------------------------------
markdown_extensions:
  - footnotes
# ------------------------------------------------
# Favicon is supposed to automatically be found:
# - in docs/img/favicon.ico
# - is a copy of docs/images/OWF-Logo-Favicon-32x32.ico
# - instead, with Material them, have a different approach (see "theme" below)
# ------------------------------------------------
# Don't enable the repo URL because irritating edit icons are shown when editing really isn't allowed
#repo_url:  https://github.com/OpenWaterFoundation/owf-app-geoprocessor-python-doc-user
# ------------------------------------------------
site_author:  OpenCDSS
site_description:  CDSS TSTool (Developer)
# ------------------------------------------------
# Use Material theme
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme:
  name: material
  favicon: 'img/favicon.ico'
# ------------------------------------------------
# The following controls how URLs are created
# - As of MkDocs 1.0 the default is true meaning URLs to a page ABC is ABC/ rather than something/ABC.html.
# - see:  https://www.mkdocs.org/user-guide/configuration/#use_directory_urls
# use_directory_urls: true
# ------------------------------------------------
